// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: albums.sql

package db

import (
	"context"
	"time"

	"api/internal/domain/shared/types"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (user_id, title, slug, cover, atlas, access, is_active, shared_emails, date_at)
SELECT u.id, $1, $2, $3, $4, $5, $6, $7, $8
FROM users u
WHERE u.id = $9 AND u.deleted_at IS NULL
RETURNING id, title, cover, date_at, atlas, access, shared_emails, direct_token, slug, is_active, user_id, created_at, updated_at, deleted_at
`

type CreateAlbumParams struct {
	Title        string       `json:"title"`
	Slug         string       `json:"slug"`
	Cover        string       `json:"cover"`
	Atlas        types.Atlas  `json:"atlas"`
	Access       types.Access `json:"access"`
	IsActive     bool         `json:"is_active"`
	SharedEmails []string     `json:"shared_emails"`
	DateAt       time.Time    `json:"date_at"`
	UserID       uuid.UUID    `json:"user_id"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.Title,
		arg.Slug,
		arg.Cover,
		arg.Atlas,
		arg.Access,
		arg.IsActive,
		arg.SharedEmails,
		arg.DateAt,
		arg.UserID,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Cover,
		&i.DateAt,
		&i.Atlas,
		&i.Access,
		&i.SharedEmails,
		&i.DirectToken,
		&i.Slug,
		&i.IsActive,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAlbum = `-- name: GetAlbum :one
SELECT id, title, cover, date_at, atlas, access, shared_emails, direct_token, slug, is_active, user_id, created_at, updated_at, deleted_at FROM albums
WHERE id = $1 AND user_id = $2
`

type GetAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAlbum(ctx context.Context, arg GetAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbum, arg.AlbumID, arg.UserID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Cover,
		&i.DateAt,
		&i.Atlas,
		&i.Access,
		&i.SharedEmails,
		&i.DirectToken,
		&i.Slug,
		&i.IsActive,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAlbumByDirectToken = `-- name: GetAlbumByDirectToken :one
SELECT id, title, cover, date_at, atlas, access, shared_emails, direct_token, slug, is_active, user_id, created_at, updated_at, deleted_at FROM albums
WHERE direct_token = $1 AND is_active AND deleted_at IS NULL
`

func (q *Queries) GetAlbumByDirectToken(ctx context.Context, directToken uuid.NullUUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByDirectToken, directToken)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Cover,
		&i.DateAt,
		&i.Atlas,
		&i.Access,
		&i.SharedEmails,
		&i.DirectToken,
		&i.Slug,
		&i.IsActive,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAlbumBySlug = `-- name: GetAlbumBySlug :one
SELECT id, title, cover, date_at, atlas, access, shared_emails, direct_token, slug, is_active, user_id, created_at, updated_at, deleted_at FROM albums
WHERE user_id = $1 AND slug = $2 AND deleted_at IS NULL
`

type GetAlbumBySlugParams struct {
	UserID    uuid.UUID `json:"user_id"`
	AlbumSlug string    `json:"album_slug"`
}

func (q *Queries) GetAlbumBySlug(ctx context.Context, arg GetAlbumBySlugParams) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumBySlug, arg.UserID, arg.AlbumSlug)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Cover,
		&i.DateAt,
		&i.Atlas,
		&i.Access,
		&i.SharedEmails,
		&i.DirectToken,
		&i.Slug,
		&i.IsActive,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAlbumsByIDs = `-- name: GetAlbumsByIDs :many
SELECT id, title, cover, date_at, atlas, access, shared_emails, direct_token, slug, is_active, user_id, created_at, updated_at, deleted_at
FROM albums a
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetAlbumsByIDs(ctx context.Context, ids []uuid.UUID) ([]Album, error) {
	rows, err := q.db.Query(ctx, getAlbumsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Cover,
			&i.DateAt,
			&i.Atlas,
			&i.Access,
			&i.SharedEmails,
			&i.DirectToken,
			&i.Slug,
			&i.IsActive,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteAlbum = `-- name: HardDeleteAlbum :one
DELETE FROM albums a
USING users u
WHERE a.user_id = u.id
  AND a.id = $1
  AND a.user_id = $2
  AND a.deleted_at IS NOT NULL
  AND u.deleted_at IS NULL
RETURNING a.id
`

type HardDeleteAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) HardDeleteAlbum(ctx context.Context, arg HardDeleteAlbumParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, hardDeleteAlbum, arg.AlbumID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAvailableAlbumIDs = `-- name: ListAvailableAlbumIDs :many
SELECT id, date_at
FROM albums
WHERE user_id = $1
  AND deleted_at IS NULL
  AND (
      (access = 'public' AND is_active)
      OR (access = 'shared' AND is_active AND $2::text = ANY(shared_emails))
  )
  AND (
      $3::timestamptz IS NULL
      OR date_at < $3::timestamptz
      OR (date_at = $3::timestamptz AND id < $4::uuid)
  )
ORDER BY date_at DESC, id DESC
LIMIT $5
`

type ListAvailableAlbumIDsParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	ViewerEmail  string             `json:"viewer_email"`
	CursorDateAt pgtype.Timestamptz `json:"cursor_date_at"`
	CursorID     uuid.NullUUID      `json:"cursor_id"`
	Limit        int32              `json:"limit"`
}

type ListAvailableAlbumIDsRow struct {
	ID     uuid.UUID `json:"id"`
	DateAt time.Time `json:"date_at"`
}

func (q *Queries) ListAvailableAlbumIDs(ctx context.Context, arg ListAvailableAlbumIDsParams) ([]ListAvailableAlbumIDsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableAlbumIDs,
		arg.UserID,
		arg.ViewerEmail,
		arg.CursorDateAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableAlbumIDsRow
	for rows.Next() {
		var i ListAvailableAlbumIDsRow
		if err := rows.Scan(&i.ID, &i.DateAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedAlbumIDs = `-- name: ListOwnedAlbumIDs :many
SELECT id, date_at
FROM albums
WHERE user_id = $1
  AND deleted_at IS NULL
  AND (
      $2::timestamptz IS NULL
      OR date_at < $2::timestamptz
      OR (date_at = $2::timestamptz AND id < $3::uuid)
  )
ORDER BY date_at DESC, id DESC
LIMIT $4
`

type ListOwnedAlbumIDsParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	CursorDateAt pgtype.Timestamptz `json:"cursor_date_at"`
	CursorID     uuid.NullUUID      `json:"cursor_id"`
	Limit        int32              `json:"limit"`
}

type ListOwnedAlbumIDsRow struct {
	ID     uuid.UUID `json:"id"`
	DateAt time.Time `json:"date_at"`
}

func (q *Queries) ListOwnedAlbumIDs(ctx context.Context, arg ListOwnedAlbumIDsParams) ([]ListOwnedAlbumIDsRow, error) {
	rows, err := q.db.Query(ctx, listOwnedAlbumIDs,
		arg.UserID,
		arg.CursorDateAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnedAlbumIDsRow
	for rows.Next() {
		var i ListOwnedAlbumIDsRow
		if err := rows.Scan(&i.ID, &i.DateAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedAlbumIDs = `-- name: ListTrashedAlbumIDs :many
SELECT id, date_at
FROM albums
WHERE user_id = $1
  AND deleted_at IS NOT NULL
  AND (
      $2::timestamptz IS NULL
      OR date_at < $2::timestamptz
      OR (date_at = $2::timestamptz AND id < $3::uuid)
  )
ORDER BY date_at DESC, id DESC
LIMIT $4
`

type ListTrashedAlbumIDsParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	CursorDateAt pgtype.Timestamptz `json:"cursor_date_at"`
	CursorID     uuid.NullUUID      `json:"cursor_id"`
	Limit        int32              `json:"limit"`
}

type ListTrashedAlbumIDsRow struct {
	ID     uuid.UUID `json:"id"`
	DateAt time.Time `json:"date_at"`
}

func (q *Queries) ListTrashedAlbumIDs(ctx context.Context, arg ListTrashedAlbumIDsParams) ([]ListTrashedAlbumIDsRow, error) {
	rows, err := q.db.Query(ctx, listTrashedAlbumIDs,
		arg.UserID,
		arg.CursorDateAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashedAlbumIDsRow
	for rows.Next() {
		var i ListTrashedAlbumIDsRow
		if err := rows.Scan(&i.ID, &i.DateAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAlbum = `-- name: RestoreAlbum :one
UPDATE albums a
SET
  deleted_at = NULL,
  updated_at = NOW(),
  slug = CASE
    WHEN EXISTS (
      SELECT 1 FROM albums AS a_active
      WHERE a_active.user_id = a.user_id
        AND a_active.slug = a.slug
        AND a_active.deleted_at IS NULL
        AND a_active.id != a.id
    )
    THEN left(a.slug, 246) || '-' || substring(md5(random()::text) from 1 for 8)
    ELSE a.slug
  END
FROM users u
WHERE a.user_id = u.id
  AND a.id = $1
  AND a.user_id = $2
  AND a.deleted_at IS NOT NULL
  AND u.deleted_at IS NULL
RETURNING a.id
`

type RestoreAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RestoreAlbum(ctx context.Context, arg RestoreAlbumParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, restoreAlbum, arg.AlbumID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const softDeleteAlbum = `-- name: SoftDeleteAlbum :one
WITH old_data AS (
  SELECT a.id, u.slug AS user_slug
  FROM albums a
  JOIN users u ON a.user_id = u.id
  WHERE a.id = $1 AND a.user_id = $2 AND a.deleted_at IS NULL AND u.deleted_at IS NULL
  FOR UPDATE OF a
)
UPDATE albums
SET deleted_at = NOW(), updated_at = NOW()
FROM old_data
WHERE albums.id = old_data.id
RETURNING albums.id, albums.title, albums.cover, albums.date_at, albums.atlas, albums.access, albums.shared_emails, albums.direct_token, albums.slug, albums.is_active, albums.user_id, albums.created_at, albums.updated_at, albums.deleted_at, old_data.user_slug
`

type SoftDeleteAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type SoftDeleteAlbumRow struct {
	Album    Album  `json:"album"`
	UserSlug string `json:"user_slug"`
}

func (q *Queries) SoftDeleteAlbum(ctx context.Context, arg SoftDeleteAlbumParams) (SoftDeleteAlbumRow, error) {
	row := q.db.QueryRow(ctx, softDeleteAlbum, arg.AlbumID, arg.UserID)
	var i SoftDeleteAlbumRow
	err := row.Scan(
		&i.Album.ID,
		&i.Album.Title,
		&i.Album.Cover,
		&i.Album.DateAt,
		&i.Album.Atlas,
		&i.Album.Access,
		&i.Album.SharedEmails,
		&i.Album.DirectToken,
		&i.Album.Slug,
		&i.Album.IsActive,
		&i.Album.UserID,
		&i.Album.CreatedAt,
		&i.Album.UpdatedAt,
		&i.Album.DeletedAt,
		&i.UserSlug,
	)
	return i, err
}

const toggleAlbumActive = `-- name: ToggleAlbumActive :one
UPDATE albums a
SET
    is_active = $1,
    updated_at = NOW()
FROM users u
WHERE a.user_id = u.id
  AND a.id = $2
  AND a.user_id = $3
  AND a.deleted_at IS NULL
  AND u.deleted_at IS NULL
RETURNING a.id, a.title, a.cover, a.date_at, a.atlas, a.access, a.shared_emails, a.direct_token, a.slug, a.is_active, a.user_id, a.created_at, a.updated_at, a.deleted_at
`

type ToggleAlbumActiveParams struct {
	IsActive bool      `json:"is_active"`
	AlbumID  uuid.UUID `json:"album_id"`
	UserID   uuid.UUID `json:"user_id"`
}

type ToggleAlbumActiveRow struct {
	Album Album `json:"album"`
}

func (q *Queries) ToggleAlbumActive(ctx context.Context, arg ToggleAlbumActiveParams) (ToggleAlbumActiveRow, error) {
	row := q.db.QueryRow(ctx, toggleAlbumActive, arg.IsActive, arg.AlbumID, arg.UserID)
	var i ToggleAlbumActiveRow
	err := row.Scan(
		&i.Album.ID,
		&i.Album.Title,
		&i.Album.Cover,
		&i.Album.DateAt,
		&i.Album.Atlas,
		&i.Album.Access,
		&i.Album.SharedEmails,
		&i.Album.DirectToken,
		&i.Album.Slug,
		&i.Album.IsActive,
		&i.Album.UserID,
		&i.Album.CreatedAt,
		&i.Album.UpdatedAt,
		&i.Album.DeletedAt,
	)
	return i, err
}

const updateAlbum = `-- name: UpdateAlbum :one
WITH old_data AS (
  SELECT a.id, a.slug AS old_slug, u.slug AS user_slug
  FROM albums a
  JOIN users u ON a.user_id = u.id
  WHERE a.id = $9 AND a.user_id = $10 AND a.deleted_at IS NULL AND u.deleted_at IS NULL
  FOR UPDATE OF a
)
UPDATE albums
SET
  title = $1,
  slug = $2,
  cover = $3,
  atlas = $4,
  access = $5,
  shared_emails = $6,
  date_at = $7,
  is_active = $8,
  updated_at = NOW()
FROM old_data
WHERE albums.id = old_data.id
RETURNING albums.id, albums.title, albums.cover, albums.date_at, albums.atlas, albums.access, albums.shared_emails, albums.direct_token, albums.slug, albums.is_active, albums.user_id, albums.created_at, albums.updated_at, albums.deleted_at, old_data.old_slug, old_data.user_slug
`

type UpdateAlbumParams struct {
	Title        string       `json:"title"`
	Slug         string       `json:"slug"`
	Cover        string       `json:"cover"`
	Atlas        types.Atlas  `json:"atlas"`
	Access       types.Access `json:"access"`
	SharedEmails []string     `json:"shared_emails"`
	DateAt       time.Time    `json:"date_at"`
	IsActive     bool         `json:"is_active"`
	AlbumID      uuid.UUID    `json:"album_id"`
	UserID       uuid.UUID    `json:"user_id"`
}

type UpdateAlbumRow struct {
	Album    Album  `json:"album"`
	OldSlug  string `json:"old_slug"`
	UserSlug string `json:"user_slug"`
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (UpdateAlbumRow, error) {
	row := q.db.QueryRow(ctx, updateAlbum,
		arg.Title,
		arg.Slug,
		arg.Cover,
		arg.Atlas,
		arg.Access,
		arg.SharedEmails,
		arg.DateAt,
		arg.IsActive,
		arg.AlbumID,
		arg.UserID,
	)
	var i UpdateAlbumRow
	err := row.Scan(
		&i.Album.ID,
		&i.Album.Title,
		&i.Album.Cover,
		&i.Album.DateAt,
		&i.Album.Atlas,
		&i.Album.Access,
		&i.Album.SharedEmails,
		&i.Album.DirectToken,
		&i.Album.Slug,
		&i.Album.IsActive,
		&i.Album.UserID,
		&i.Album.CreatedAt,
		&i.Album.UpdatedAt,
		&i.Album.DeletedAt,
		&i.OldSlug,
		&i.UserSlug,
	)
	return i, err
}

const updateAlbumDirectToken = `-- name: UpdateAlbumDirectToken :one
WITH old_data AS (
  SELECT a.id, a.direct_token AS old_direct_token
  FROM albums a
  JOIN users u ON a.user_id = u.id
  WHERE a.id = $2 AND a.user_id = $3 AND a.deleted_at IS NULL AND u.deleted_at IS NULL
  FOR UPDATE OF a
)
UPDATE albums
SET
  direct_token = $1,
  updated_at = NOW()
FROM old_data
WHERE albums.id = old_data.id
RETURNING albums.id, albums.title, albums.cover, albums.date_at, albums.atlas, albums.access, albums.shared_emails, albums.direct_token, albums.slug, albums.is_active, albums.user_id, albums.created_at, albums.updated_at, albums.deleted_at, old_data.old_direct_token
`

type UpdateAlbumDirectTokenParams struct {
	DirectToken uuid.NullUUID `json:"direct_token"`
	AlbumID     uuid.UUID     `json:"album_id"`
	UserID      uuid.UUID     `json:"user_id"`
}

type UpdateAlbumDirectTokenRow struct {
	Album          Album         `json:"album"`
	OldDirectToken uuid.NullUUID `json:"old_direct_token"`
}

func (q *Queries) UpdateAlbumDirectToken(ctx context.Context, arg UpdateAlbumDirectTokenParams) (UpdateAlbumDirectTokenRow, error) {
	row := q.db.QueryRow(ctx, updateAlbumDirectToken, arg.DirectToken, arg.AlbumID, arg.UserID)
	var i UpdateAlbumDirectTokenRow
	err := row.Scan(
		&i.Album.ID,
		&i.Album.Title,
		&i.Album.Cover,
		&i.Album.DateAt,
		&i.Album.Atlas,
		&i.Album.Access,
		&i.Album.SharedEmails,
		&i.Album.DirectToken,
		&i.Album.Slug,
		&i.Album.IsActive,
		&i.Album.UserID,
		&i.Album.CreatedAt,
		&i.Album.UpdatedAt,
		&i.Album.DeletedAt,
		&i.OldDirectToken,
	)
	return i, err
}
