// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"api/internal/domain/shared/types"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID           uuid.UUID          `json:"id"`
	Title        string             `json:"title"`
	Cover        string             `json:"cover"`
	DateAt       time.Time          `json:"date_at"`
	Atlas        types.Atlas        `json:"atlas"`
	Access       types.Access       `json:"access"`
	SharedEmails []string           `json:"shared_emails"`
	DirectToken  uuid.NullUUID      `json:"direct_token"`
	Slug         string             `json:"slug"`
	IsActive     bool               `json:"is_active"`
	UserID       uuid.UUID          `json:"user_id"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type RefreshToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	IsConsumed bool               `json:"is_consumed"`
	Ip         string             `json:"ip"`
	Ua         string             `json:"ua"`
	Location   string             `json:"location"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt  time.Time          `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Role      types.Role         `json:"role"`
	Avatar    string             `json:"avatar"`
	Slug      string             `json:"slug"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
