// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CleanupRefreshTokens(ctx context.Context) error
	ConsumeRefreshTokenByHash(ctx context.Context, tokenHash string) (pgconn.CommandTag, error)
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error
	DeleteOtherRefreshTokensForUser(ctx context.Context, arg DeleteOtherRefreshTokensForUserParams) error
	DeleteRefreshTokenByID(ctx context.Context, arg DeleteRefreshTokenByIDParams) (string, error)
	GetActiveRefreshTokensForUser(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error)
	GetAlbum(ctx context.Context, arg GetAlbumParams) (Album, error)
	GetAlbumByDirectToken(ctx context.Context, directToken uuid.NullUUID) (Album, error)
	GetAlbumBySlug(ctx context.Context, arg GetAlbumBySlugParams) (Album, error)
	GetAlbumsByIDs(ctx context.Context, ids []uuid.UUID) ([]Album, error)
	GetAvailableUser(ctx context.Context, id uuid.UUID) (User, error)
	GetAvailableUserBySlug(ctx context.Context, slug string) (User, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	HardDeleteAlbum(ctx context.Context, arg HardDeleteAlbumParams) (uuid.UUID, error)
	HardDeleteUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error)
	ListAvailableAlbumIDs(ctx context.Context, arg ListAvailableAlbumIDsParams) ([]ListAvailableAlbumIDsRow, error)
	ListOwnedAlbumIDs(ctx context.Context, arg ListOwnedAlbumIDsParams) ([]ListOwnedAlbumIDsRow, error)
	ListTrashedAlbums(ctx context.Context, arg ListTrashedAlbumsParams) ([]Album, error)
	RestoreAlbum(ctx context.Context, arg RestoreAlbumParams) (uuid.UUID, error)
	RestoreUser(ctx context.Context, userID uuid.UUID) (RestoreUserRow, error)
	SoftDeleteAlbum(ctx context.Context, arg SoftDeleteAlbumParams) (SoftDeleteAlbumRow, error)
	SoftDeleteUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error)
	ToggleAlbumActive(ctx context.Context, arg ToggleAlbumActiveParams) (ToggleAlbumActiveRow, error)
	UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (UpdateAlbumRow, error)
	UpdateAlbumDirectToken(ctx context.Context, arg UpdateAlbumDirectTokenParams) (UpdateAlbumDirectTokenRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
