// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const cleanupRefreshTokens = `-- name: CleanupRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < NOW()
   OR (is_consumed = true AND updated_at < NOW() - INTERVAL '24 hours')
`

func (q *Queries) CleanupRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupRefreshTokens)
	return err
}

const consumeRefreshTokenByHash = `-- name: ConsumeRefreshTokenByHash :execresult
UPDATE refresh_tokens
SET is_consumed = true, updated_at = NOW()
WHERE token_hash = $1 AND is_consumed = false
`

func (q *Queries) ConsumeRefreshTokenByHash(ctx context.Context, tokenHash string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, consumeRefreshTokenByHash, tokenHash)
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at, ip, ua, location)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	Ip        string    `json:"ip"`
	Ua        string    `json:"ua"`
	Location  string    `json:"location"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.Ua,
		arg.Location,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAllRefreshTokensForUser = `-- name: DeleteAllRefreshTokensForUser :exec
DELETE FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllRefreshTokensForUser, userID)
	return err
}

const deleteOtherRefreshTokensForUser = `-- name: DeleteOtherRefreshTokensForUser :exec
DELETE FROM refresh_tokens
WHERE user_id = $1 AND token_hash != $2
`

type DeleteOtherRefreshTokensForUserParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) DeleteOtherRefreshTokensForUser(ctx context.Context, arg DeleteOtherRefreshTokensForUserParams) error {
	_, err := q.db.Exec(ctx, deleteOtherRefreshTokensForUser, arg.UserID, arg.TokenHash)
	return err
}

const deleteRefreshTokenByID = `-- name: DeleteRefreshTokenByID :one
DELETE FROM refresh_tokens
WHERE id = $1 AND user_id = $2
RETURNING token_hash
`

type DeleteRefreshTokenByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteRefreshTokenByID(ctx context.Context, arg DeleteRefreshTokenByIDParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteRefreshTokenByID, arg.ID, arg.UserID)
	var token_hash string
	err := row.Scan(&token_hash)
	return token_hash, err
}

const getActiveRefreshTokensForUser = `-- name: GetActiveRefreshTokensForUser :many
SELECT id, user_id, token_hash, is_consumed, ip, ua, location, updated_at, expires_at, created_at
FROM refresh_tokens
WHERE user_id = $1 AND is_consumed = false AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) GetActiveRefreshTokensForUser(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getActiveRefreshTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.IsConsumed,
			&i.Ip,
			&i.Ua,
			&i.Location,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, is_consumed, ip, ua, location, updated_at, expires_at, created_at FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IsConsumed,
		&i.Ip,
		&i.Ua,
		&i.Location,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
