// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"api/internal/domain/shared/types"
	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, role, slug)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, role, avatar, slug, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email    string     `json:"email"`
	Username string     `json:"username"`
	Role     types.Role `json:"role"`
	Slug     string     `json:"slug"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Role,
		arg.Slug,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Avatar,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAvailableUser = `-- name: GetAvailableUser :one
SELECT id, username, email, role, avatar, slug, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAvailableUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getAvailableUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Avatar,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAvailableUserBySlug = `-- name: GetAvailableUserBySlug :one
SELECT id, username, email, role, avatar, slug, created_at, updated_at, deleted_at FROM users WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAvailableUserBySlug(ctx context.Context, slug string) (User, error) {
	row := q.db.QueryRow(ctx, getAvailableUserBySlug, slug)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Avatar,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :one
DELETE FROM users WHERE id = $1 RETURNING id
`

func (q *Queries) HardDeleteUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, hardDeleteUser, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users
SET
    deleted_at = NULL,
    updated_at = NOW(),
    slug = CASE
        WHEN EXISTS (
            SELECT 1 FROM users AS u_active
            WHERE u_active.slug = users.slug
              AND u_active.deleted_at IS NULL
              AND u_active.id != users.id
        )
        THEN left(users.slug, 246) || '-' || substring(md5(random()::text) from 1 for 8)
        ELSE users.slug
    END
WHERE users.id = $1 AND users.deleted_at IS NOT NULL
RETURNING id, slug
`

type RestoreUserRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

func (q *Queries) RestoreUser(ctx context.Context, userID uuid.UUID) (RestoreUserRow, error) {
	row := q.db.QueryRow(ctx, restoreUser, userID)
	var i RestoreUserRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

func (q *Queries) SoftDeleteUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateUser = `-- name: UpdateUser :one
WITH old_data AS (
    SELECT id, slug FROM users
    WHERE users.id = $1 AND users.deleted_at IS NULL
    FOR UPDATE
) UPDATE users SET
    username = $2,
    slug = $3,
    updated_at = NOW()
FROM old_data
WHERE users.id = old_data.id
RETURNING users.id, users.username, users.email, users.role, users.avatar, users.slug, users.created_at, users.updated_at, users.deleted_at, old_data.slug AS old_slug
`

type UpdateUserParams struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Slug     string    `json:"slug"`
}

type UpdateUserRow struct {
	User    User   `json:"user"`
	OldSlug string `json:"old_slug"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Username, arg.Slug)
	var i UpdateUserRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.Role,
		&i.User.Avatar,
		&i.User.Slug,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.OldSlug,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (email, username, avatar)
VALUES ($1, $2, $3)
ON CONFLICT (email)
DO UPDATE SET
    avatar = EXCLUDED.avatar
WHERE users.deleted_at IS NULL
RETURNING id, username, email, role, avatar, slug, created_at, updated_at, deleted_at
`

type UpsertUserParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Email, arg.Username, arg.Avatar)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Avatar,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
